#!/usr/bin/env python3

# Copyright 2021 Elliot Jordan
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
RepoLasso.py
https://github.com/homebysix/repo-lasso

A tool that enables maintainers of GitHub organizations to submit
nearly-identical pull requests in bulk across all organization repositories.

Typical workflow:
┌─────────────────────────────────────────────────────────────────────┐
│                                                                     │
│  ┌────────┐   ┌──────────┐   ┌──────────┐    ┌──────┐   ┌─────────┐ │
└─►│  sync  ├──►│  branch  ├──►│  commit  ├─┬─►│  pr  ├──►│  reset  ├─┘
   └────────┘   └──────────┘   └──────────┘ │  └──────┘   └─────────┘
                                 ▲          │
                                 └──────────┘

For more information and usage walkthrough, see the README.
"""

import sys
from textwrap import dedent
from time import time

from packaging.version import Version

from shared import (  # noqa: F401
    CONFIG_PATH,
    __version__,
    branch,
    build_argument_parser,
    check,
    colors,
    commit,
    cprint,
    get_config,
    pr,
    readable_time,
    report,
    reset,
    status,
    sync,
)


def main():
    """Main process."""

    start = time()

    # Parse command line arguments.
    argparser = build_argument_parser()
    args = argparser.parse_args()

    if "func" not in args.__dict__:
        # Show help if no verb was provided.
        argparser.print_help()
        sys.exit(0)

    # Generated by pyfiglet - "slant" font
    logo = f"""
               ____                   __
              / __ \\___  ____  ____  / /   ____ _______________
             / /_/ / _ \\/ __ \\/ __ \\/ /   / __ `/ ___/ ___/ __ \\
            / _, _/  __/ /_/ / /_/ / /___/ /_/ (__  |__  ) /_/ /
           /_/ |_|\\___/ .___/\\____/_____/\\__,_/____/____/\\____/
                     /_/                            {__version__}
           """
    cprint(dedent(logo), colors.HEADER)

    if Version(__version__) < Version("1.0.0"):
        cprint(
            "WARNING: RepoLasso is still experimental. Verify all changes "
            "manually before submitting pull requests in bulk.\n",
            colors.WARNING,
        )

    # Read configuration or prompt user for configuration items.
    cprint("CONFIGURATION", colors.OKBLUE)
    config = get_config(CONFIG_PATH, args)

    # Kick off desired verb.
    args.func.main(args, config)

    # Print run duration.
    cprint("\nFinished in %s." % readable_time(time() - start), colors.HEADER)


if __name__ == "__main__":
    main()
